# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Ej. Dr. Lic. Ing. Mtr. Mba', max_length=20, verbose_name='Abreviatura de tu nivel académico'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Agrega tu fecha de nacimiento para tener una mejor experiencia de usuario y para comprobar que no eres menor de 13 años, de lo contrario tu cuenta puede ser bloqueada.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, help_text='Escribe tu último título académico ej. "Doctorado en medicina", "Licenciatura en enfermería".', max_length=100, verbose_name='Profesión o título académico'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Teléfono ej. +503 2502 6108'),
        ),
    ]
