# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 20:08
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190403_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pictureS',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_picture_directory_path),
        ),
    ]
