# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190403_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pictureS',
            new_name='profile_pictures',
        ),
    ]
