# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190331_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
    ]
