# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 16:16
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190331_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_directory_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='courses.Course'),
        ),
    ]
