# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190408_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
