# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_certificate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_seen', to='courses.Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mis lecciones',
                'verbose_name_plural': 'Mis lecciones',
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
    ]
